services:
  autogen-app:
    build: .
    image: autogen-saas
    container_name: autogen-saas_container
    stdin_open: true  # Keeps stdin open for interaction
    tty: true  # Allocates a pseudo-TTY to provide an interactive terminal
    env_file:
      - .env
    ports:
      - "4200:4200"
    networks:
      - my-app-network
    volumes:
      - ./workspace:/workspace
      - ./dwh_agents:/workspace/dwh_agents
      - ./chat_agents:/workspace/chat_agents
      - ./orchestrator.py:/workspace/orchestrator.py
      - ./public:workspace/public
      - ./WA_Fn-UseC_-HR-Employee-Attrition.csv:/workspace/WA_Fn-UseC_-HR-Employee-Attrition.csv
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    # command: python orchestrator.py
    command: python -m chainlit run orchestrator.py --host 0.0.0.0 --port 4200
    # command: python -m chainlit hello --host 0.0.0.0 --port 8000
    # command: python -m chainlit hello
    # command: python -m chainlit --version

networks:
  my-app-network:
    name: my-app-network
    external: true

